[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["dgel <douwegelling@gmail.com>"]
edition = "2018"

[dependencies]
combine = "^4.4"
gumdrop = "^0.8"
regex = "1"
bitvec = "^0.19"
nalgebra = "^0.23"
divrem = "0.1"
scan_fmt = "^0.2.2"
anyhow = "^1.0"
ndarray = "^0.14"
